### PR TITLE
Add MacOS Cmd-C shortcut and update pack script

### PR DESCRIPTION
**Pull request by xanoni**
- Add .gitignore
- Add Cmd+C shortcut for MacOS
- Update pack.sh for MacOS

### CODE REVIEW

**Comment by xanoni** [comment]
Another user requested this here and I also found it useful: https://github.com/ColdSpirit0/FastCopyLinks/issues/4

**Comment by mstraa** [comment]
Lol I just did the same dev on the Addon but you're PR is cleaner, I delete mine !

**Comment by mstraa** [comment]
+1 for the merge and update on the firefox extension page

**Comment by ColdSpirit0** [comment]
Hi! Sorry for long time didn't check your PR. I checked code and it looks good, and works on Windows, but cant test it on MacOS, so I will trust @mstraa =)

**Comment by xanoni** [comment]
Thank you. It worked on my Mac ;-)

**Pull request merged**
